<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>carla_autoware_launch</name>
  <version>0.1.0</version>
  <description>Autoware launch files and configurations for CARLA simulation</description>
  <maintainer email="user@example.com">User</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <exec_depend>autoware_launch</exec_depend>
  <exec_depend>tier4_localization_launch</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
