#!/usr/bin/env bash
# Derive acb_launch's copy of autoware_launch's tier4_perception_component.launch.xml.
#
# The copy exists for one change: upstream hard-codes
#   <arg name="traffic_light_recognition/fusion_only" value="false"/>
# inside its include of tier4_perception_launch/perception.launch.xml, and an <include> of
# the component cannot override it. fusion_only drops the camera branch of traffic light
# recognition (camera_info relay, map-based detector, classifier) and keeps fusion, the
# arbiter and the crosswalk estimator -- which acb needs, because acb publishes the signal
# state from CARLA on external/traffic_signals (carla-scenario-bridge roadmap 015). Here
# it becomes a launch argument, default false as upstream.
#
#   scripts/sync_perception_component.sh          regenerate the copy from the installed upstream
#   scripts/sync_perception_component.sh --check  exit 1 if the copy differs from what it would regenerate
#
# Run --check after an Autoware upgrade; regenerate if it fails.
set -euo pipefail
here="$(cd "$(dirname "$0")/.." && pwd)"
upstream="${AUTOWARE_LAUNCH_SHARE:-/opt/autoware/1.5.0/share/autoware_launch}/launch/components/tier4_perception_component.launch.xml"
copy="$here/src/acb_launch/launch/components/tier4_perception_component.launch.xml"
hardcoded='<arg name="traffic_light_recognition/fusion_only" value="false"/>'
[ -f "$upstream" ] || { echo "no upstream component at $upstream"; exit 2; }
[ "$(grep -cF "$hardcoded" "$upstream")" = 1 ] || {
    echo "upstream no longer hard-codes fusion_only exactly once; revisit this copy"; exit 2; }

generate() {
    sed \
        -e "s|$hardcoded|<arg name=\"traffic_light_recognition/fusion_only\" value=\"\$(var traffic_light_recognition/fusion_only)\"/>|" \
        -e "0,/<launch>/s|<launch>|<launch>\n  <!-- GENERATED by acb scripts/sync_perception_component.sh from autoware_launch's\n       tier4_perception_component.launch.xml; do not edit by hand. Only change:\n       traffic_light_recognition/fusion_only is an argument instead of hard-coded false. -->\n  <arg name=\"traffic_light_recognition/fusion_only\" default=\"false\" description=\"skip the camera branch of traffic light recognition; keep fusion, arbiter and crosswalk estimator\"/>|" \
        "$upstream"
}

if [ "${1:-}" = "--check" ]; then
    if diff -q <(generate) "$copy" >/dev/null; then echo "perception component copy matches upstream"; else
        echo "perception component copy is out of date with $upstream; run scripts/sync_perception_component.sh"; exit 1; fi
else
    generate > "$copy"; echo "wrote $copy"
fi
